[package]
name = "mctp-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
argh = "0.1.12"
async-io = "2.3.4"
async-net = "2.0.0"
futures-io = "0.3.30"
log = "0.4.22"
simplelog = "0.12.2"
smol = "2.0.0"
mctp = { git = "http://github.com/CodeConstruct/mctp-rs", tag = "dev/mctp-stack-v0.1.0", package = "mctp" }
mctp-estack = { git = "http://github.com/CodeConstruct/mctp-rs", tag = "dev/mctp-stack-v0.1.0", package = "mctp-estack" }
mctp-standalone = { git = "http://github.com/CodeConstruct/mctp-rs", tag = "dev/mctp-stack-v0.1.0", package = "mctp-standalone" }
embedded-io-adapters = { version = "0.6", features = [ "futures-03" ] }
embedded-io-async = { version = "0.6" }
usbredirparser = { git = "https://github.com/CodeConstruct/usbredir-rs", branch = "main", package = "usbredirparser" }
polling = "3.7.4"
futures = "0.3.31"
async-channel = "2.3.1"
critical-section = { version = "1.2.0", features = ["std"] }
uuid = { version = "1.16.0", features = ["v4"] }
